# Generated by Django 4.2 on 2024-07-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
    ]
