# Generated by Django 4.2 on 2024-07-25 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_created_alter_comment_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='massage',
            new_name='message',
        ),
    ]
