# Generated by Django 4.2 on 2024-09-03 04:53

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_image_image_file_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='birth_date',
            new_name='birth_of_date',
        ),
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='بایو'),
        ),
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[600, 400], upload_to='account_images/', verbose_name='تصویر'),
        ),
    ]
